name: Build and Publish Docker Image

on:
  push:
    branches:
      - main   # ou a branch que você usa

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Puxar o código do repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build e push da imagem
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: laizask/atividade-formativa:latest
